### ISSUE TITLE
Running graphql get-schema project_name gives an error, because of incorrect relative path of prisma.yml

### ISSUE THREAD

**Issue by artem-korolev** [prisma/graphql-config#100]
I have this file structure:

- workspace
   .graphqlconfig
   - servers
   --- prisma
   --- app
   --- admin
   - clients
   --- relay-native
   --- react-graphql

**.graphqlconfig**:
```json
{
	"projects": {
		"graphql": {
			"schemaPath": "servers/app/src/generated/prisma.graphql",
			"extensions": {
				"prisma": "servers/prisma/prisma.yml"
			}
		}
	}
}
```

So that .graphqlconfig is placed in the root of workspace.
I run this:
```bash
cd servers/app
graphql get-schema -p graphql
× servers/prisma/prisma.yml could not be found.
```

if I update my config with this line:
"prisma": "../../servers/prisma/prisma.yml"
everything works okay then.
So I guess its a bug, that should be fixed

I want to have at least 2 applications for one prisma server.. its usually 1) app 2) admin... pretty logical.. different endpoints.. different auth rules, security flows and so on.
and I want auto update schemas in all applications when I change prisma schema... current approach support updating only one app.. well.. maybe i'm wrong.. this type of project structure looks to me pretty logical, but i'm not able to configure it properly for some reason

**Comment by marktani** [comment]
I'm closing this in favor of https://github.com/graphql-cli/graphql-cli/issues/340 now. I'm not sure if this is a bug, and if it is in `graphql-config` or `graphql-cli`, but we'll find out 🙂
